json.id product.id
json.name product.name
json.description product.description
json.in_stock? product.in_stock?
json.price product.price
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total product.total
json.image_url product.image_url
json.created_at product.created_at
json.updated_at product.updated_at